application:
  name: Atlas

spark:
  session_timezone: UTC

customer:
  customers_topic: atlas.customer.public.customers
  customer_addresses_topic: atlas.customer.public.customer_addresses
  customer_consents_topic: atlas.customer.public.customer_consents